services:

  preflight:
    container_name: preflight
    build:
      context: preflight
      additional_contexts:
        shared: shared
    volumes:
    - /srv/shared:/srv/shared
    env_file:
    - preflight/.env

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    ports:
    - "0.0.0.0:8989:8989"
    volumes:
    - /srv/sonarr:/config
    - /srv/shared:/srv/shared
    env_file:
    - shared/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    ports:
    - "0.0.0.0:7878:7878"
    volumes:
    - /srv/radarr:/config
    - /srv/shared:/srv/shared
    env_file:
    - shared/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:7878 || exit 1
    restart: unless-stopped

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr
    ports:
    - "0.0.0.0:8686:8686"
    volumes:
    - /srv/lidarr:/config
    - /srv/shared:/srv/shared
    env_file:
    - shared/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:8686 || exit 1
    restart: unless-stopped

  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    ports:
    - "0.0.0.0:8787:8787"
    volumes:
    - /srv/readarr:/config
    - /srv/shared:/srv/shared
    env_file:
    - shared/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:8787 || exit 1
    restart: unless-stopped

  listenarr:
    container_name: listenarr
    image: lscr.io/linuxserver/readarr:develop
    ports:
    - "0.0.0.0:8484:8484"
    volumes:
    - /srv/listenarr:/config
    - /srv/shared:/srv/shared
    env_file:
    - shared/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:8787 || exit 1
    restart: unless-stopped

  watch:
    container_name: watch
    build: watch
    user: "${USER_ID}:${GROUP_ID}"
    ports:
    - "0.0.0.0:11180:80"
    volumes:
    - /srv/watch/data:/data/caddy
    - /srv/watch/config:/config/caddy
    - /srv/shared/sonarr:/srv/shared/sonarr:ro
    - /srv/shared/radarr:/srv/shared/radarr:ro
    env_file:
    - watch/.env
    depends_on:
      preflight:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost/healthcheck || exit 1
    restart: unless-stopped
